backend = "glx";

blur-method = "none";
animations = false;
vsync = false;

wintypes:
{
  dock = { shadow = false; };
  tooltip = { shadow = false; };
  popup_menu = { opacity = 0.95; };
};

shadow = true;
shadow-radius = 18;
shadow-offset-x = 0;
shadow-offset-y = 5;
shadow-opacity = 0.22;

shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Rofi'"
];

fading = true;
fade-in-step = 0.035;
fade-out-step = 0.035;
fade-delta = 8;

fade-exclude = [
  "name = 'Lantern Lock'",
  "role = 'saver_lantern'",
  "class_g = 'xsecurelock'"
];

corner-radius = 14;
round-borders = 1;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

detect-client-opacity = true;
detect-rounded-corners = true;

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

opacity-rule = [
  "90:class_g = 'awesome'",
];
